apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: mp-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: traefik/whoami:v1.10.2
        imagePullPolicy: IfNotPresent
        name: echo
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
  namespace: mp-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpcbin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      containers:
      - image: moul/grpcbin:latest
        imagePullPolicy: Always
        name: grpcbin
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ws-test
  name: ws-test
  namespace: mp-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ws-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ws-test
    spec:
      containers:
      - image: inanimate/echo-server:latest
        imagePullPolicy: Always
        name: echo-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: mp-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/protocol: grpc
  name: grpcbin
  namespace: mp-demo
spec:
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: grpcbin
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ws-test
  name: ws
  namespace: mp-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ws-test
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: 'false'
  name: echo
  namespace: mp-demo
spec:
  ingressClassName: kong
  rules:
  - host: echo.103.240.25.21.sslip.io
    http:
      paths:
      - backend:
          service:
            name: echo
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/protocols: grpcs
    konghq.com/strip-path: 'false'
  name: grpcbin
  namespace: mp-demo
spec:
  ingressClassName: kong
  rules:
  - host: grpc.103.240.25.21.sslip.io
    http:
      paths:
      - backend:
          service:
            name: grpcbin
            port:
              number: 9000
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: 'false'
  name: ws
  namespace: mp-demo
spec:
  ingressClassName: kong
  rules:
  - host: ws.103.240.25.21.sslip.io
    http:
      paths:
      - backend:
          service:
            name: ws
            port:
              number: 80
        path: /
        pathType: Prefix
